repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      # - id: check-added-large-files
      #   args: ['--maxkb=10000']
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-symlinks
      - id: check-executables-have-shebangs
      - id: check-xml
      - id: check-docstring-first
      # - id: double-quote-string-fixer

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.11
