# SPDX-FileCopyrightText: 2024 Dogan Ulus <dogan.ulus@bogazici.edu.tr>
# SPDX-License-Identifier: MPL-2.0

version = 1

[[annotations]]
path = [
  ".devcontainer/**",
  ".github/**",
  ".gitignore",
  ".gitattributes",
  ".pre-commit-config.yaml",
  ".vscode/**",
  "containers/**",
  "README.adoc"
]
SPDX-FileCopyrightText = ["2024 Dogan Ulus <dogan.ulus@bogazici.edu.tr>"]
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = [
  "xom3d/**",
]
SPDX-FileCopyrightText = ["2024 Dogan Ulus <dogan.ulus@bogazici.edu.tr>"]
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = [
  "scripts/**",
]
SPDX-FileCopyrightText = ["2024 Dogan Ulus <dogan.ulus@bogazici.edu.tr>"]
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = [
  "python/openx_assets/**",
  "pyproject.toml",
]
SPDX-FileCopyrightText = ["2024 Dogan Ulus <dogan.ulus@bogazici.edu.tr>"]
SPDX-License-Identifier = "GPL-3.0-or-later"
