# SPDX-FileCopyrightText: 2024 Dogan Ulus <dogan.ulus@bogazici.edu.tr>
# SPDX-License-Identifier: MPL-2.0

version = 1

[[annotations]]
path = [
  ".devcontainer/**",
  ".github/**",
  ".gitignore",
  "README.md"
]
SPDX-FileCopyrightText = ["2024 Dogan Ulus <dogan.ulus@bogazici.edu.tr>"]
SPDX-License-Identifier = "MPL-2.0"

