version = 1

[[annotations]]
path = [
    "m1_generic_police_tackleberry/**",
]
SPDX-FileCopyrightText = [
    "2025 Dogan Ulus <dogan.ulus@bogazici.edu.tr>",
    "2022 mk2design <https://sketchfab.com/mk2design>, licensed under CC-BY-4.0"
]
SPDX-License-Identifier = "MPL-2.0 AND CC-BY-4.0"
