version = 1

[[annotations]]
path = [
    "police_bmw_x1_2016/**",
]
SPDX-FileCopyrightText = [
    "2025 Dogan Ulus <dogan.ulus@bogazici.edu.tr>",
    "2022 mk2design <https://sketchfab.com/mk2design>, licensed under CC-BY-4.0"
]
SPDX-License-Identifier = "MPL-2.0 AND CC-BY-4.0"

[[annotations]]
path = [
    "m1_volvo_v60_polestar_2013/**",
]
SPDX-FileCopyrightText = [
    "2025 Dogan Ulus <dogan.ulus@bogazici.edu.tr>",
    "2022 myedsu <https://sketchfab.com/myedsu>, licensed under CC-BY-4.0"
]
SPDX-License-Identifier = "MPL-2.0 AND CC-BY-4.0"
