name: buildah-build-devel
on:
  push:
    paths:
      - containers/esmini-assets-devel/**
      - .github/workflows/buildah-build-devel.yml # Self-trigger
  workflow_dispatch:

env:
  REGISTRY: ghcr.io/bounverif
  IMAGE_NAME: esmini-assets
  HOSTARCH: amd64
  PLATFORM: linux-amd64
  VERSION: latest

permissions:
  contents: read
  packages: write

jobs:
  buildah-build:
    name: Build container images
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}
      cancel-in-progress: true

    steps:
      - name: Install container tools
        run: sudo apt-get install podman buildah jq

      - name: Prepare environment variables
        run: |
          echo "HOSTARCH=$(podman info --format='{{.Host.Arch}}')" >> $GITHUB_ENV
          echo "PLATFORM=$(podman info --format='{{.Version.OsArch}}' | sed 's/\//-/g')" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build devel container image
        id: build-devel
        uses: redhat-actions/buildah-build@v2
        with:
          context: ./containers
          image: esmini
          tags: ${{ env.VERSION }}-devel ${{ env.VERSION }}-devel-${{ env.HOSTARCH }}
          layers: true
          oci: true
          build-args: |
            VERSION=${{ env.VERSION }}
          extra-args: |
            --target esmini-assets-devel
          containerfiles: |
            ./containers/esmini-assets-devel/Dockerfile

      - name: Push to GitHub Container Repository
        if: github.ref == 'refs/heads/main'
        id: push-devel-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ steps.build-devel.outputs.image }}
          tags: ${{ env.VERSION }}-devel-${{ env.HOSTARCH }}
          digestfile: ${{ runner.temp }}/digest-esmini-assets-devel-${{ env.VERSION }}-${{ env.PLATFORM }}

      - name: Upload digests
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: digest-esmini-${{ env.VERSION }}-${{ env.PLATFORM }}
          path: ${{ runner.temp }}/digest-*
          if-no-files-found: error
          retention-days: 1
          compression-level: 0 # no compression

  buildah-merge:
    name: Merge container images
    runs-on: ubuntu-24.04
    needs: buildah-build
    if: github.ref == 'refs/heads/main' && always()
    steps:
      # - run: mkdir -p $TMPDIR
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digest-*
          merge-multiple: true

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest list for esmini-assets-devel
        run: |
          MANIFEST=esmini-devel
          FULL_IMAGE_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          buildah manifest create $MANIFEST
          for digest in ${{ runner.temp }}/digests/digest-esmini-assets-devel-*; do
            echo "Adding $(cat $digest)"
            buildah manifest add $MANIFEST $FULL_IMAGE_NAME@$(cat $digest)
          done
          buildah manifest push --all $MANIFEST docker://$FULL_IMAGE_NAME:${{ env.VERSION }}-devel
