name: OpenX Assets Release

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run"
        required: false
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

permissions:
  contents: write

jobs:
  release-assets:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bounverif/openx-assets:latest-builder
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Prepare environment variables
        run: |
            echo "VERSION=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Download and install FBX SDK at runtime
        run: |
          export FBXSDK_INSTALL_PREFIX="/tmp/install"
          mkdir -p ${FBXSDK_INSTALL_PREFIX}
          sh /usr/local/bin/fbxsdk-install.sh
          mv ${FBXSDK_INSTALL_PREFIX}/lib/release/* /usr/local/lib
          rm -rf ${FBXSDK_INSTALL_PREFIX}
          ldconfig

      - name: Install OpenX Assets Python package
        run: pip install . --break-system-packages

      - name: Build and bundle OpenX assets
        run: make bundle

      - name: Create GitHub release
        if: github.ref == 'refs/heads/main' && inputs.dry_run != 'true'
        uses: softprops/action-gh-release@v2
        with:
          files: openx-assets.zip
          name: "OpenX Assets"
          tag_name: ${{ env.VERSION }}
          make_latest: true
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
