name: release
on:
  workflow_dispatch:
  schedule:
    - cron: "12 5 1-7 * 1"

permissions:
  contents: write

jobs:
  release-assets:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/bounverif/esmini-assets:latest-builder
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download and install FBX SDK
        run: |
          export FBXSDK_INSTALL_PREFIX="/tmp/install"
          mkdir -p ${FBXSDK_INSTALL_PREFIX}
          sh /usr/local/bin/fbxsdk-install.sh
          mv ${FBXSDK_INSTALL_PREFIX}/lib/release/* /usr/local/lib
          rm -rf ${FBXSDK_INSTALL_PREFIX}
          ldconfig
      - name: Build and package assets
        run: make esmini-assets
